wandb:
  project: "MLOPS"
  api_key: ""
  run_name: "MLOPS"



hyperparameters:
  learning_rate: 0.0031622776
  warmup_steps: 100
  weight_decay: 0.0001
  optimizer_type: "sgd"
  momentum: 0.95
  beta1: 0.9
  beta2: 0.999