FROM pytorch/pytorch:2.5.1-cuda11.8-cudnn9-runtime
WORKDIR /app

COPY requirements_gpu.txt /app/
COPY requirements.txt /app/

RUN pip install -r requirements.txt
RUN pip install -r requirements_gpu.txt


COPY mlops.py /app/


CMD ["python", "mlops.py"]
